A bunch of bug fixes...
* Removed the question of "New install" vs "Replace a node" from the Install Manifest run (will have it be one in the same when the bugs are ironed out)
* Updates the install manifest confirmation page to load the MAC addresses from the anvil-map-network into the 'to_set' variables when the 'ifn-bridge1' device exits to make re-runs cleaner without re-prompting the user to map interfaces.
* Significantly overhauled how the fence stuff is parsed when reading in fence details. I am not sure what I was smoking when I first wrote that code... Big one was using proper references to link methods to devices instead of ... whatever I was doing.
* Fixed a bug where IPMI failed to start because it decided to laugh in the face of LSB compliance.
* Broke out setting 'root' and 'ricci' passwords into two functions as ccs was complaining about the ricci password not being set when we ran 'ccs_config_validate' (or sometime shortly after).
* Fixed a bug in the IPMI code where the LAN channel and user ID went 1 too high from the $x++ at the end of the loop.
* Fixed a bug where setting the IPMI IP wasn't detected because the regex matched the network status (dhcp v. static)
* Moved 'dhcpd' into the run-on-start section of the striker-installer. Will revert this later when I add the enable/disable boot target button in Striker proper.
* Added a function to the striker-installer ISO mount function to make sure the ISO is in /etc/fstab so that it mounts on boot.
* Fixed the generated kickstart script to a) clear 'all' partitions as it left the DRBD ones behind and b) have a proper start of the %post script that handles partitioning.
* Fixed a small bug where the PXE menu always showed '^5) ' for the RHEL node option.
* Fixed striker-installer to setup an iptables rule to allow incoming tftp connections.

Known Bug:
* Right now, a re-run of the installer fails because it doesn't see the previously-created DRBD partitions. Tomorrow's task...

Signed-off-by: Madison Kelly (digimer) <digimer@alteeve.ca>

diff --git a/tools/striker-installer b/tools/striker-installer
--- a/tools/striker-installer
+++ b/tools/striker-installer
@@ -62,9 +62,9 @@ my $conf = {
 		# 'disable' is processes.
 		# NOTE: 'haldaemon' needs to restart before 'acpid' will work,
 		#       if 'acpid' was just installed.
-		enable			=>	["iptables", "httpd", "haldaemon", "acpid", "tomcat6", "guacd", "network", "ntpd", "xinetd"],
+		enable			=>	["dhcpd", "iptables", "httpd", "haldaemon", "acpid", "tomcat6", "guacd", "network", "ntpd", "xinetd"],
 		# These will be both chkconfig off'ed and stopped.
-		disable			=>	["ip6tables", "dhcpd", "NetworkManager"],
+		disable			=>	["ip6tables", "NetworkManager"],
 	},
 	directory	=>	{
 		apache			=>	"/etc/httpd",
@@ -1215,23 +1215,50 @@ sub mount_iso
 	my ($conf, $source, $target) = @_;
 	
 	# First make sure the target isn't already mounted.
-	my $shell_call = "$conf->{executable}{mount} -o loop $source $target; echo \"mount:\$?\"";
-	#print "[ Debug ] - shell_call: [$shell_call]\n";
+	my $iso_file   = ($source =~ /^.*\/(.*)$/)[0];
+	my $shell_call = "if \$(grep -q $source /etc/fstab);
+			then
+				echo 'already added to /etc/fstab';
+			else
+				echo '$source $target auto loop 0 0' >> /etc/fstab;
+				echo 'added ISO to /etc/fstab';
+			fi;
+			if \$(mount | grep -q $iso_file);
+			then
+				echo 'already mounted';
+			else
+				mount $target;
+				echo mount:$?; 
+			fi";
+	print "[ Debug ] - shell_call: [$shell_call]\n";
 	open (my $file_handle, '-|', "$shell_call") || die "Failed to call: [$shell_call], error was: $!\n";
 	while(<$file_handle>)
 	{
 		chomp;
 		my $line = $_;
+		if ($line =~ /already added/)
+		{
+			print "- ISO file: [$iso_file] already in '/etc/fstab'.\n";
+		}
+		if ($line =~ /added ISO/)
+		{
+			print "- ISO file: [$iso_file] added to '/etc/fstab'.\n";
+		}
+		if ($line =~ /already mounted/)
+		{
+			print "- ISO file: [$iso_file] Was already mounted!\n";
+		}
 		if ($line =~ /^mount:(\d+)/)
 		{
 			my $rc = $1;
 			if ($rc == 0)
 			{
-				print "- Mounted successfully\n";
+				print "- ISO file: [$iso_file] was mounted successfully.\n";
 			}
-			elsif ($rc == 32)
+			else
 			{
-				print "- Was already mounted!\n";
+				print "[ Warning ] - ISO file: [$iso_file] appears to have NOT mounted!\n";
+				print "[ Warning ]   Return code was: [$rc], expected '0'.\n";
 			}
 		}
 		#print "- Output: [$line]\n";
@@ -1345,7 +1372,10 @@ sed -i 's/GSSAPIAuthentication yes/#GSSAPIAuthentication yes/' /etc/ssh/sshd_con
 		$os_directory = "rhel6";
 		$say_os       = "RHEL";
 	}
-	print "
+	### TODO: Enable an option to setup this machine as a local repo
+	if (0)
+	{
+		$kickstart .= "
 cat > /etc/yum.repos.d/striker-$conf->{sys}{hostname}-$os.repo << EOF
 [striker-$conf->{sys}{hostname}-bcn-$os]
 name=Striker $conf->{sys}{hostname}'s $say_os 6 BCN repo.
@@ -1359,7 +1389,9 @@ baseurl=http://$conf->{network}{ifn}{ip}/$os_directory/x86_64/img/
 enabled=1
 gpgcheck=0
 EOF
-
+";
+	}
+	$kickstart .= "
 \%end
 
 ### Script to setup partitions.
@@ -1387,7 +1419,7 @@ if grep -q sdb /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=sdb
+clearpart --all --drives=sdb
 ignoredisk --only-use=sdb
 bootloader --location=mbr --driveorder=sdb
 
@@ -1402,7 +1434,7 @@ elif grep -q sda /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=sda
+clearpart --all --drives=sda
 ignoredisk --only-use=sda
 bootloader --location=mbr --driveorder=sda
 
@@ -1417,7 +1449,7 @@ elif grep -q vda /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=vda
+clearpart --all --drives=vda
 ignoredisk --only-use=vda
 bootloader --location=mbr --driveorder=vda
 
@@ -1446,7 +1478,7 @@ if grep -q sdb /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=sdb
+clearpart --all --drives=sdb
 ignoredisk --only-use=sdb
 bootloader --location=mbr --driveorder=sdb
 
@@ -1461,7 +1493,7 @@ elif grep -q sda /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=sda
+clearpart --all --drives=sda
 ignoredisk --only-use=sda
 bootloader --location=mbr --driveorder=sda
 
@@ -1476,7 +1508,7 @@ elif grep -q vda /proc/partitions; then
 cat >> /tmp/part-include <<END
 
 zerombr
-clearpart --linux --drives=vda
+clearpart --all --drives=vda
 ignoredisk --only-use=vda
 bootloader --location=mbr --driveorder=vda
 
@@ -1620,7 +1652,7 @@ LABEL generic-centos-striker-basic-bios
 		$i++;
 		$default_config .= "
 LABEL generic-rhel-striker-basic-bios
-        MENU LABEL ^5) Striker Dashboard - Traditional BIOS - RHEL 6
+        MENU LABEL ^$i) Striker Dashboard - Traditional BIOS - RHEL 6
 	TEXT HELP
 		Installs a generic Striker dashboard using RHEL 6. Will create a
 		traditional /boot + MBR install for systems with traditional BIOSes.
@@ -2422,6 +2454,7 @@ sub configure_iptables
 		backup_file($conf, $conf->{path}{iptables});
 	}
 	
+	my $tftp_open  = 0;
 	my $http_open  = 0;
 	my $https_open = 0;
 	print "- Reading the current firewall configuration.\n";
@@ -2433,6 +2466,11 @@ sub configure_iptables
 		chomp;
 		my $line = $_;
 		#print "- Output: [$line]\n";
+		if (($line =~ /--state NEW/) && ($line =~ /--dport 69/) && ($line =~ /ACCEPT/))
+		{
+			print "- Trivial FTP is already enabled.\n";
+			$tftp_open = 1;
+		}
 		if (($line =~ /--state NEW/) && ($line =~ /--dport 80/) && ($line =~ /ACCEPT/))
 		{
 			print "- Standard web access is already enabled.\n";
@@ -2446,6 +2484,20 @@ sub configure_iptables
 	}
 	close $file_handle;
 	
+	if (not $tftp_open)
+	{
+		print "- Opening access for trivial FTP (needed for PXE booting).\n";
+		my $shell_call =  "$conf->{executable}{iptables} -I INPUT -m state --state NEW -p tcp --dport 69 -j ACCEPT && ";
+		   $shell_call .= "$conf->{executable}{iptables} -I INPUT -m state --state NEW -p udp --dport 69 -j ACCEPT";
+		open (my $file_handle, '-|', "$shell_call") || die "Failed to call: [$shell_call], error was: $!\n";
+		while(<$file_handle>)
+		{
+			chomp;
+			my $line = $_;
+			print "- Output: [$line]\n";
+		}
+		close $file_handle;
+	}
 	if (not $http_open)
 	{
 		print "- Opening access for standard web access.\n";
